### ISSUE TITLE
Add pngquant binaries

### ISSUE THREAD

**Issue by GoDamage** [previousnext/containers#68]
Building on https://github.com/previousnext/containers/pull/65

Can we add pngquant to the apt install? This will give us a lossy png compression option for greater size reduction, as per the findings in https://www.previousnext.com.au/blog/better-image-optimisation-drupal. 

Package is just named 'pngquant'

**Comment by nicksantamaria** [comment]
For future reference - we are keeping optipng so that site builders have a choice of lossy v lossless optimisation.
